using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FN.Framtal.Database
{
    public class K72VG_A_RFRAMTAL1
    {
        public string _0030 { get; set; }
        public string _0040 { get; set; }
        public string _0041 { get; set; }
        public string _0042 { get; set; }
        public bool _0110 { get; set; }
        public bool _0115 { get; set; }
        public bool _0130 { get; set; }
        public bool _0135_ { get; set; }
        public bool _0140 { get; set; }
        public bool _0150 { get; set; }
        public bool _0160 { get; set; }
        public bool _0170 { get; set; }
        public bool _0180 { get; set; }
        public bool _0190 { get; set; }
        public string _0220 { get; set; }
        public bool _0230 { get; set; }
        public bool _0240 { get; set; }
        public bool _0250 { get; set; }
        public bool _0260 { get; set; }
        public bool _0270 { get; set; }
        public bool _0280 { get; set; }
        public int _0500 { get; set; }
        public int _0510 { get; set; }
        public int _0520 { get; set; }
        public int _0530 { get; set; }
        public int _0540 { get; set; }
        public int _0550 { get; set; }
        public int _0560 { get; set; }
        public int _0570 { get; set; }
        public int _0580 { get; set; }
        public int _0590 { get; set; }
        public int _0600 { get; set; }
        public int _0610 { get; set; }
        public int _0620 { get; set; }
        public int _0630 { get; set; }
        public int _0640 { get; set; }
        public int _0650 { get; set; }
        public int _0660 { get; set; }
        public int _0670 { get; set; }
        public int _0680 { get; set; }
        public int _0690 { get; set; }
        public int _0695 { get; set; }
        public int _0900 { get; set; }
        public int _0910 { get; set; }
        public int _0920 { get; set; }
        public int _0930 { get; set; }
        public int _0950 { get; set; }
        public int _0960 { get; set; }
        public int _0970 { get; set; }
        public int _1010 { get; set; }
        public int _1020 { get; set; }
        public int _1030 { get; set; }
        public int _1040 { get; set; }
        public int _1050 { get; set; }
        public int _1060 { get; set; }
        public int _1070 { get; set; }
        public int _1090 { get; set; }
        public int _2010 { get; set; }
        public int _2020 { get; set; }
        public int _2030 { get; set; }
        public int _2040 { get; set; }
        public int _2050 { get; set; }
        public int _2060 { get; set; }
        public int _2070 { get; set; }
        public int _2080 { get; set; }
        public int _2090 { get; set; }
        public int _2100 { get; set; }
        public int _2110 { get; set; }
        public int _2120 { get; set; }
        public int _2130 { get; set; }
        public int _2140 { get; set; }
        public int _2150 { get; set; }
        public int _2160 { get; set; }
        public int _2170 { get; set; }
        public int _2180 { get; set; }
        public int _2190 { get; set; }
        public int _2200 { get; set; }
        public int _2210 { get; set; }
        public int _2220 { get; set; }
        public int _2230 { get; set; }
        public int _2240 { get; set; }
        public int _2250 { get; set; }
        public int _2260 { get; set; }
        public int _2270 { get; set; }
        public int _2275 { get; set; }
        public int _2280 { get; set; }
        public int _2290 { get; set; }
        public int _2300 { get; set; }
        public int _2310 { get; set; }
        public int _2320 { get; set; }
        public int _2330 { get; set; }
        public int _2340 { get; set; }
        public int _2350 { get; set; }
        public int _2360 { get; set; }
        public int _2370 { get; set; }
        public int _2380 { get; set; }
        public int _2390 { get; set; }
        public int _2400 { get; set; }
        public int _2410 { get; set; }
        public int _2420 { get; set; }
        public int _2430 { get; set; }
        public int _2440 { get; set; }
        public int _2450 { get; set; }
        public int _2460 { get; set; }
        public int _2470 { get; set; }
        public int _2480 { get; set; }
        public int _2490 { get; set; }
        public int _2500 { get; set; }
        public int _2510 { get; set; }
        public int _2520 { get; set; }
        public int _2530 { get; set; }
        public int _2800 { get; set; }
        public int _2810 { get; set; }
        public int _2820 { get; set; }
        public int _2990 { get; set; }
        public int _3005 { get; set; }
        public int _3010 { get; set; }
        public int _3015 { get; set; }
        public int _3020 { get; set; }
        public int _3030 { get; set; }
        public int _3040 { get; set; }
        public int _3050 { get; set; }
        public int _3070 { get; set; }
        public int _3080 { get; set; }
        public int _3090 { get; set; }
        public int _3100 { get; set; }
        public int _3110 { get; set; }
        public int _3120 { get; set; }
        public int _3130 { get; set; }
        public int _3140 { get; set; }
        public int _3150 { get; set; }
        public int _3160 { get; set; }
        public int _3170 { get; set; }
        public int _3180 { get; set; }
        public int _3190 { get; set; }
        public int _3290 { get; set; }
        public int _3590 { get; set; }
        public int _3600 { get; set; }
        public int _3610 { get; set; }
        public int _3620 { get; set; }
        public int _3630 { get; set; }
        public int _3640 { get; set; }
        public int _3650 { get; set; }
        public int _3662 { get; set; }
        public int _3670 { get; set; }
        public int _3671 { get; set; }
        public int _3680 { get; set; }
        public int _3690 { get; set; }
        public int _3700 { get; set; }
        public int _3990 { get; set; }
        public int _4010 { get; set; }
        public int _4011 { get; set; }
        public int _4020 { get; set; }
        public int _4030 { get; set; }
        public int _4040 { get; set; }
        public int _4050 { get; set; }
        public int _4060 { get; set; }
        public int _4070 { get; set; }
        public int _4080 { get; set; }
        public int _4090 { get; set; }
        public int _4091 { get; set; }
        public int _4100 { get; set; }
        public int _4115 { get; set; }
        public int _4130 { get; set; }
        public int _4140 { get; set; }
        public int _4150 { get; set; }
        public int _4160 { get; set; }
        public int _4310 { get; set; }
        public int _4320 { get; set; }
        public int _4330 { get; set; }
        public int _4340 { get; set; }
        public int _4350 { get; set; }
        public int _4360 { get; set; }
        public int _4370 { get; set; }
        public int _4380 { get; set; }
        public int _4390 { get; set; }
        public int _4391 { get; set; }
        public int _4450 { get; set; }
        public int _4530 { get; set; }
        public int _4540 { get; set; }
        public int _4550 { get; set; }
        public int _4560 { get; set; }
        public int _4570 { get; set; }
        public int _4580 { get; set; }
        public int _4590 { get; set; }
        public int _4600 { get; set; }
        public int _4610 { get; set; }
        public int _4990 { get; set; }
        public int _3085 { get; set; }
        public int _4025 { get; set; }
        public int _4092 { get; set; }
        public int _4093 { get; set; }
        public string _4433 { get; set; }
        public int _0980 { get; set; }
        public int _0981 { get; set; }
        public int _0982 { get; set; }
        public int _2171 { get; set; }
        public int _2173 { get; set; }
        public int _2351 { get; set; }
        public int _2353 { get; set; }
        public int _2401 { get; set; }
        public int _2403 { get; set; }
        public int RAL_TENGING_VID_405 { get; set; }
        public string _0200 { get; set; }
        public string _0210 { get; set; }

        public string RAL_SVFE { get; set; }
        public string RAL_NAFN { get; set; }
        public string RAL_HEIM { get; set; }
        public string RAL_PONR { get; set; }
        public bool RAL_LOGG_END_FRAMTAL_UNNID_AF { get; set; }
        public bool RAL_BOKARI_SKODM_FRAMT_UNN_AF { get; set; }
        public bool RAL_ADK_VERKTAKI_FRAMT_UNN_AF { get; set; }
        public bool RAL_EIG_STASM_FRAMTAL_UNNID_AF { get; set; }
        public bool RAL_ARITUN_SKODMANNS_ARSREIKN { get; set; }
        public bool RAL_ARIT_AN_FYRIRVARA_LOGG_END { get; set; }
        public bool RAL_ARIT_M_FYRIRVARA_LOGG_END { get; set; }
        public bool RAL_ARITUN_AN_ALITS_LOGG_END { get; set; }
        public bool RAL_NEIKV_ARITUN_LOGG_END { get; set; }
        public bool RAL_ARIT_AN_ENDURSKOD_LOGG_END { get; set; }
        public bool RAL_ARSREI_EKKI_GERDUR_LOGGEND { get; set; }
        public string RAL_ADAL_VSK_NUMER { get; set; }
        public bool RAL_EINSTAKL_M_REKST_TEG_REKST { get; set; }
        public bool RAL_SKATTSK_LOGAD_TEG_REKSTRAR { get; set; }
        public bool RAL_SAMREKST_EKKI_SJ_TEG_REKST { get; set; }
        public bool RAL_TAKM_SKATTSK_TEGUND_REKST { get; set; }
        public int RVS_SKSK_V_AN_VSK_BOKH_ARS_245 { get; set; }
        public int RVS_SKSK_V_AN_VSK_BOKH_ARS_14 { get; set; }
        public int RVS_UNDANTH_V_BOKHALD_ARSREIKN { get; set; }
        public int RVS_UTSKATT_BOKHALD_ARSREIKN { get; set; }
        public int RVS_INNSKATT_BOKHALD_ARSREIKN { get; set; }
        public int RVS_SKSK_V_AN_VSK_SKYRSLUR_245 { get; set; }
        public int RVS_SKSK_V_AN_VSK_SKYRSLUR_14 { get; set; }
        public int RVS_UNDANTH_VELTA_VSK_SKYRSLUR { get; set; }
        public int RVS_UTSKATT_VSK_SKYRSLUR { get; set; }
        public int RVS_INNSKATT_VSK_SKYRSLUR { get; set; }
        public int RVS_SKASK_VELTA_AN_VSK_MIS_245 { get; set; }
        public int RVS_SKATSK_VELTA_AN_VSK_MIS_14 { get; set; }
        public int RVS_UNDANTHEGIN_VELTA_MISM { get; set; }
        public int RVS_UTSKATT_MISM { get; set; }
        public int RVS_INNSKATT_MISM { get; set; }
        public int RYV_BAKFAERDUR_INNSKATT { get; set; }
        public int RYV_EIGNF_KOSTN_INNSKATT { get; set; }
        public int RYV_EIGNF_FJARMLEIGA_INNSKATT { get; set; }
        public int RYV_INNFLUTNINGUR_INNSKATT { get; set; }
        public int RYV_245_KAUPV_INNFL_REKSTFJARM { get; set; }
        public int RYV_ANN_HANDF_INNSK_SKV_YFIRL { get; set; }
        public int RAG_HREINAR_TEKJUR { get; set; }
        public int RAG_YFIRF_TAP_TIL_NAESTA_ARS { get; set; }
        public int RAG_HREIN_EIGN { get; set; }
        public int RAG_SKULDIR_UMFRAM_EIGNIR { get; set; }
        public int RAG_IDNADARMALAGJALDSSTOFN { get; set; }
        public int RAG_JOFNUNARVERDM_HLUTABREFA { get; set; }
        public int RAG_ARDSTEKJUR_SAMEIGNARFELAGS { get; set; }
        public int RTE_VSK_SKYLD_SALA_245 { get; set; }
        public int RTE_VSK_SKYLD_SALA_14 { get; set; }
        public int RTE_VELTA_UNDANTHEGIN_VSK { get; set; }
        public int RTE_STARFSEMI_UNDANTHEGIN_VSK { get; set; }
        public int RTE_SOLUHAGNADUR { get; set; }
        public int RTE_ADRAR_TEKJUR { get; set; }
        public int RTE_LEIDR_REKSTRART_MTT_ARSREI { get; set; }
        public int RTE_REKSTRARTEKJUR_SAMTALS { get; set; }
        public int RGV_HRAEFNISKAUP_INNLANDS_245 { get; set; }
        public int RGV_HRAEFNISKAUP_INNANLANDS_14 { get; set; }
        public int RGV_HRAEFNISKAUP_INNANLANDS_0 { get; set; }
        public int RGV_HRAEFNISKAUP_ERLEND_245 { get; set; }
        public int RGV_HRAEFNISKAUP_ERLEND_14 { get; set; }
        public int RGV_HRAEFNISKAUP_ERLEND_0 { get; set; }
        public int RGV_REKSTRARV_ANN_FRKOSTN_245 { get; set; }
        public int RGV_REKSTRARV_ANNAR_FRKOSTN_14 { get; set; }
        public int RGV_REKSTRARV_ANNAR_FRKOSTN_0 { get; set; }
        public int RGV_VORUKAUP_INNANLANDS_245 { get; set; }
        public int RGV_VORUKAUP_INNANLANDS_14 { get; set; }
        public int RGV_VORUKAUP_INNANLANDS_0 { get; set; }
        public int RGV_VORUKAUP_ERLEND_245 { get; set; }
        public int RGV_VORUKAUP_ERLEND_14 { get; set; }
        public int RGV_VORUKAUP_ERLEND_0 { get; set; }
        public int RGV_ADKEYPT_VINNA_T_ENDURS_245 { get; set; }
        public int RGV_ADKEYPT_VINNA_TIL_ENDURS_0 { get; set; }
        public int RGV_HUSALEIGA_245 { get; set; }
        public int RGV_HUSALEIGA_0 { get; set; }
        public int RGV_VIDHALD_FASTEIGNA_245 { get; set; }
        public int RGV_VIDHALD_FASTEIGNA_0 { get; set; }
        public int RGV_ANN_REKSTRARK_FASTEIGN_245 { get; set; }
        public int RGV_ANN_REKSTRARK_FASTEIGN_14 { get; set; }
        public int RGV_ANNAR_REKSTRARK_FASTEIGN_0 { get; set; }
        public int RGV_SOLUKOSTNADUR_245 { get; set; }
        public int RGV_SOLUKOSTNADUR_0 { get; set; }
        public int RGV_REKST_FLUTNINGATAEKJA_245 { get; set; }
        public int RGV_REKSTUR_FLUTNINGATAEKJA_14 { get; set; }
        public int RGV_REKSTUR_FLUTNINGATAEKJA_0 { get; set; }
        public int RGV_ADK_AKSTUR_ANN_FLKOSTN_245 { get; set; }
        public int RGV_ADK_AKSTUR_ANNAR_FLKOSTN_0 { get; set; }
        public int RGV_FERDAKOSTNADUR_245 { get; set; }
        public int RGV_FERDAKOSTNADUR_14 { get; set; }
        public int RGV_FERDAKOSTNADUR_0 { get; set; }
        public int RGV_YMIS_ADKEYPT_THJONUSTA_245 { get; set; }
        public int RGV_YMIS_ADKEYPT_THJONUSTA_0 { get; set; }
        public int RGV_ANN_SKRIFST_STJORNKOST_245 { get; set; }
        public int RGV_ANN_SKRIFST_STJORNKOST_14 { get; set; }
        public int RGV_ANNAR_SKRIFST_STJORNKOST_0 { get; set; }
        public int RGV_LAUSAFJARLEIG_FJMLEIGA_245 { get; set; }
        public int RGV_LAUSAFJARLEIGA_FJMLEIGA_0 { get; set; }
        public int RGV_GJALDF_REKSTRARFJARMUN_245 { get; set; }
        public int RGV_GJALDF_REKSTRARFJARMUNIR_0 { get; set; }
        public int RGV_VIDHALDSKOSTNADUR_245 { get; set; }
        public int RGV_VIDHALDSKOSTNADUR_0 { get; set; }
        public int RGV_STARFSMANNAT_KOSTN_245 { get; set; }
        public int RGV_STARFSMANNAT_KOSTN_14 { get; set; }
        public int RGV_STARFSMANNAT_KOSTN_0 { get; set; }
        public int RGV_AFSKRIFAD_VIDSKIPTAKR_245 { get; set; }
        public int RGV_AFSKRIFADAR_VIDSKIPTAKR_14 { get; set; }
        public int RGV_AFSKRIFADAR_VIDSKIPTAKR_0 { get; set; }
        public int RGV_YMIS_ANNAR_KOSTN_245 { get; set; }
        public int RGV_YMIS_ANNAR_KOSTN_14 { get; set; }
        public int RGV_YMIS_ANNAR_KOSTN_0 { get; set; }
        public int RGV_SAMTALS_245 { get; set; }
        public int RGV_SAMTALS_14 { get; set; }
        public int RGV_SAMTALS_0 { get; set; }
        public int RGA_SAMTAL_GJALDASUNDURLID_VSK { get; set; }
        public int RGA_BIRGD_FUL_VARA_UPPHAF_RARS { get; set; }
        public int RGA_BIRGD_ANN_VARA_UPPHAF_RARS { get; set; }
        public int RGA_BIRGD_FULLU_VARA_LOK_RARS { get; set; }
        public int RGA_BIRGD_ANNAR_VARA_LOK_RARS { get; set; }
        public int RGA_LAUN { get; set; }
        public int RGA_DAGPENINGAR { get; set; }
        public int RGA_BIFREIDASTYRKIR { get; set; }
        public int RGA_ONNUR_LAUN { get; set; }
        public int RGA_REIKNAD_ENDURGJALD { get; set; }
        public int RGA_LAUNATENGD_GJOLD { get; set; }
        public int RGA_REIKNUD_HLUNNINDI { get; set; }
        public int RGA_GJAFIR_FRAMLOG { get; set; }
        public int RGA_SOLUTAP { get; set; }
        public int RGA_FYRNINGAR { get; set; }
        public int RGA_KOST_SKV_REKYFIRL_FOLKBIFR { get; set; }
        public int RGA_REKSTUR_FOLKSBIFR { get; set; }
        public int RGA_RISNA_GJAFIR_VIDSKIPTAMENN { get; set; }
        public int RGA_LEIDR_LAUNALIDA_MTT_ARSR { get; set; }
        public int RGA_EIGNF_REKSTRARGJOLD { get; set; }
        public int RGA_LEIDR_KROF_ABYRGD_MTT_ARSR { get; set; }
        public int RGA_ADR_LEID_REKSTRGJ_MTT_ARSR { get; set; }
        public int RGA_REKSTRARGJOLD_SAMTALS { get; set; }
        public int RGA_REKSTRARTEK_MIN_REKSTRARGJ { get; set; }
        public int RTG_VAXTATEKJUR { get; set; }
        public int RTG_GENGISHAGN_GENGISTAP { get; set; }
        public int RTG_ADRAR_FJARMUNATEKJUR { get; set; }
        public int RTG_VAXTAGJOLD { get; set; }
        public int RTG_ONNUR_FJARMAGNSGJOLD { get; set; }
        public int RTG_VERDBREYTINGATEKJUR_GJOLD { get; set; }
        public int RTG_OREGLULEGAR_TEKJUR { get; set; }
        public int RTG_OREGLULEGAR_GJOLD { get; set; }
        public int RTG_HLUTD_RAFK_OSJALFST_SKAAD { get; set; }
        public int RTG_TEKJUSKATTAR_EIGNARSKATTAR { get; set; }
        public int RTG_ONNUR_GJOLD { get; set; }
        public int RTG_HAGNADUR_TAP_ARSREIKN { get; set; }
        public int RLR_FREST_TEKJ_61GR_UPPH_RARS { get; set; }
        public int RLR_FREST_TEKJUR_61GR_LOK_RARS { get; set; }
        public int RLR_SKATTLEG_LEIDR_SOLHAGN_TAP { get; set; }
        public int RLR_FRESTUN_SOLUHAGNADAR { get; set; }
        public int RLR_SOLUHAGN_FRA_FYRRI_ARUM { get; set; }
        public int RLR_SKATTALEG_LEIDR_VERDBREYTF { get; set; }
        public int RLR_SKATTALEG_LEIDR_FYRNINGA { get; set; }
        public int RLR_AUKAFYRN_SKATTALOG { get; set; }
        public int RLR_SKATTL_LEIDR_KROFUR_ABYRGD { get; set; }
        public int RLR_NIDURF_VKR_UPPH_RARS_SKATT { get; set; }
        public int RLR_NIDURF_VKR_LOK_RARS_SKATTL { get; set; }
        public int RLR_SKATT_LEIDR_HL_RAFK_OSJALF { get; set; }
        public int RLR_FENGINN_ARDUR_TIL_FRADRATT { get; set; }
        public int RLR_ALAG_V_FR_SOLUH_FJFESJ_VSJ { get; set; }
        public int RLR_OFRADRATTARB_OPINBER_GJOLD { get; set; }
        public int RLR_OSKATTSKYLDAR_TEKJUR { get; set; }
        public int RLR_OFRADRATTARB_KOSTNADUR { get; set; }
        public int RLR_SKL_LEIDR_V_GR_EFTIRLAUNA { get; set; }
        public int RLR_SKL_LEIDR_V_EFTIRLAUSKULDB { get; set; }
        public int RLR_SKL_LEID_SOLUH_SOLUT_HLUBR { get; set; }
        public int RLR_SKL_LEID_V_FJARMOGNUNLEIGU { get; set; }
        public int RLR_SKL_L_HLUD_AFK_HLUDF_DOTTF { get; set; }
        public int RLR_SKL_LEIDR_AFANGAINNL_TEKNA { get; set; }
        public int RLR_SKL_LEIDR_V_VERKLOKAADFERD { get; set; }
        public int RLR_BAKF_VERDLEIDR_SKATTSKULDB { get; set; }
        public int RLR_ADRAR_SKL_LEIDRETT_HAEKKUN { get; set; }
        public int RLR_ADRAR_SKL_LEIDRETT_LAEKKUN { get; set; }
        public int RLR_HAGN_TAP_FYRIR_YFIRF_TAP { get; set; }
        public int RLR_FRAMREIK_ONO_TAP_AR_MIN_10 { get; set; }
        public int RLR_FRAMREIK_ONOT_TAP_AR_MIN_9 { get; set; }
        public int RLR_FRAMREIK_ONOT_TAP_AR_MIN_8 { get; set; }
        public int RLR_FRAMREIK_ONOT_TAP_AR_MIN_7 { get; set; }
        public int RLR_FRAMREIK_ONOT_TAP_AR_MIN_6 { get; set; }
        public int RLR_FRAMREIK_ONOT_TAP_AR_MIN_5 { get; set; }
        public int RLR_FRAMREIK_ONOT_TAP_AR_MIN_4 { get; set; }
        public int RLR_FRAMREIK_ONOT_TAP_AR_MIN_3 { get; set; }
        public int RLR_FRAMREIK_ONOT_TAP_AR_MIN_2 { get; set; }
        public int RLR_FRAMREIK_ONOT_TAP_AR_MIN_1 { get; set; }
        public int RLR_HR_TEKJUR_YFIRF_TAP_T_N_AR { get; set; }
        public int RGA_MOTFRAMLAG_LIFEYRISSJOD { get; set; }
        public int RLR_FRESTUN_SOLUH_HLUTABREF { get; set; }
        public int RLR_NIDURF_BI_UPPH_RARS_SKATT { get; set; }
        public int RLR_NIDURF_BI_LOK_RARS_SKATTL { get; set; }
        public string RAL_ATHUGASEMDIR { get; set; }
        public int RAG_STOFN_TRYGGINGAGJ_STADGR { get; set; }
        public int RAG_STOFN_TRYGGGJALD_UT_STADGR { get; set; }
        public int RGV_ADK_ERL_VINNA_T_ENDURS_245 { get; set; }
        public int RGV_ADK_ERL_VINNA_TIL_ENDURS_0 { get; set; }
        public int RGV_YMIS_ADK_THJONUSTA_245_ERL { get; set; }
        public int RGV_YMIS_ADK_THJONUSTA_0_ERL { get; set; }
        public int RGV_LAUSFLEIG_FJMLEIGA_245_ERL { get; set; }
        public int RGV_LAUSAFJLEIG_FJMLEIGA_0_ERL { get; set; }
        public string RAL_ADAL_ATVINNUGR_NUMER_2004 { get; set; }
        public string RAL_LEIDR_ATVINNUGR_NUMER_2004 { get; set; }







    }
}
