using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FN.Framtal.Database
{
    public class RSK408_BUSTOFN
    {
        public int N408_MJOLKURKYR_SKATTMAT { get; set; }
        public int N408_MJOLKURKYR_FJ_ARSBYRJUN { get; set; }
        public int N408_MJOLKURKYR_MATSV_BYRJUN { get; set; }
        public int N408_MJOLKURKYR_FJ_ARSLOK { get; set; }
        public int N408_MJOLKURKYR_MATS_ARSLOK { get; set; }
        public int N408_MJOLKURKYR_FJ_VANHALDAS { get; set; }
        public int N408_MJOLKURKYR_FJ_KEYPT { get; set; }
        public int N408_MJOLKURKYR_KAUPVERD { get; set; }
        public int N408_HOLDAKYR_SKATTMAT { get; set; }
        public int N408_HOLDAKYR_FJ_ARSBYRJUN { get; set; }
        public int N408_HOLDAKYR_MATSV_BYRJUN { get; set; }
        public int N408_HOLDAKYR_FJ_ARSLOK { get; set; }
        public int N408_HOLDAKYR_MATS_ARSLOK { get; set; }
        public int N408_HOLDAKYR_FJ_VANHALDAS { get; set; }
        public int N408_HOLDAKYR_FJ_KEYPT { get; set; }
        public int N408_HOLDAKYR_KAUPVERD { get; set; }
        public int N408_KVIGUR_15Y_SKATTMAT { get; set; }
        public int N408_KVIGUR_15Y_FJ_ARSBYRJUN { get; set; }
        public int N408_KVIGUR_15Y_MATSV_BYRJUN { get; set; }
        public int N408_KVIGUR_15Y_FJ_ARSLOK { get; set; }
        public int N408_KVIGUR_15Y_MATS_ARSLOK { get; set; }
        public int N408_KVIGUR_15Y_FJ_VANHALDAS { get; set; }
        public int N408_KVIGUR_15Y_FJ_KEYPT { get; set; }
        public int N408_KVIGUR_15Y_KAUPVERD { get; set; }
        public int N408_GELDNEYTI_SKATTMAT { get; set; }
        public int N408_GELDNEYTI_FJ_ARSBYRJUN { get; set; }
        public int N408_GELDNEYTI_MATSV_BYRJUN { get; set; }
        public int N408_GELDNEYTI_FJ_ARSLOK { get; set; }
        public int N408_GELDNEYTI_MATS_ARSLOK { get; set; }
        public int N408_GELDNEYTI_FJ_VANHALDAS { get; set; }
        public int N408_GELDNEYTI_FJ_KEYPT { get; set; }
        public int N408_GELDNEYTI_KAUPVERD { get; set; }
        public int N408_KALFAR_U05_SKATTMAT { get; set; }
        public int N408_KALFAR_U05_FJ_ARSBYRJUN { get; set; }
        public int N408_KALFAR_U05_MATSV_BYRJUN { get; set; }
        public int N408_KALFAR_U05_FJ_ARSLOK { get; set; }
        public int N408_KALFAR_U05_MATS_ARSLOK { get; set; }
        public int N408_KALFAR_U05_FJ_VANHALDAS { get; set; }
        public int N408_KALFAR_U05_FJ_KEYPT { get; set; }
        public int N408_KALFAR_U05_KAUPVERD { get; set; }
        public int N408_AER_SAUDIR_SKATTMAT { get; set; }
        public int N408_AER_SAUDIR_FJ_ARSBYRJUN { get; set; }
        public int N408_AER_SAUDIR_MATSV_BYRJUN { get; set; }
        public int N408_AER_SAUDIR_FJ_ARSLOK { get; set; }
        public int N408_AER_SAUDIR_MATS_ARSLOK { get; set; }
        public int N408_AER_SAUDIR_FJ_VANHALDAS { get; set; }
        public int N408_AER_SAUDIR_FJ_KEYPT { get; set; }
        public int N408_AER_SAUDIR_KAUPVERD { get; set; }
        public int N408_HRUTAR_SKATTMAT { get; set; }
        public int N408_HRUTAR_FJ_ARSBYRJUN { get; set; }
        public int N408_HRUTAR_MATSV_BYRJUN { get; set; }
        public int N408_HRUTAR_FJ_ARSLOK { get; set; }
        public int N408_HRUTAR_MATS_ARSLOK { get; set; }
        public int N408_HRUTAR_FJ_VANHALDAS { get; set; }
        public int N408_HRUTAR_FJ_KEYPT { get; set; }
        public int N408_HRUTAR_KAUPVERD { get; set; }
        public int N408_GEMLINGAR_SKATTMAT { get; set; }
        public int N408_GEMLINGAR_FJ_ARSBYRJUN { get; set; }
        public int N408_GEMLINGAR_MATSV_BYRJUN { get; set; }
        public int N408_GEMLINGAR_FJ_ARSLOK { get; set; }
        public int N408_GEMLINGAR_MATS_ARSLOK { get; set; }
        public int N408_GEMLINGAR_FJ_VANHALDAS { get; set; }
        public int N408_GEMLINGAR_FJ_KEYPT { get; set; }
        public int N408_GEMLINGAR_KAUPVERD { get; set; }
        public int N408_HROSS_14Y_SKATTMAT { get; set; }
        public int N408_HROSS_14Y_FJ_ARSBYRJUN { get; set; }
        public int N408_HROSS_14Y_MATSV_BYRJUN { get; set; }
        public int N408_HROSS_14Y_FJ_ARSLOK { get; set; }
        public int N408_HROSS_14Y_MATS_ARSLOK { get; set; }
        public int N408_HROSS_14Y_FJ_VANHALDAS { get; set; }
        public int N408_HROSS_14Y_FJ_KEYPT { get; set; }
        public int N408_HROSS_14Y_KAUPVERD { get; set; }
        public int N408_HROSS_5_13_SKATTMAT { get; set; }
        public int N408_HROSS_5_13_FJ_ARSBYRJUN { get; set; }
        public int N408_HROSS_5_13_MATSV_BYRJUN { get; set; }
        public int N408_HROSS_5_13_FJ_ARSLOK { get; set; }
        public int N408_HROSS_5_13_MATS_ARSLOK { get; set; }
        public int N408_HROSS_5_13_FJ_VANHALDAS { get; set; }
        public int N408_HROSS_5_13_FJ_KEYPT { get; set; }
        public int N408_HROSS_5_13_KAUPVERD { get; set; }
        public int N408_FULLT_REIDH_5_13_SKATTMAT { get; set; }
        public int N408_FULLT_REIDH_5_13_FJ_BYRJU { get; set; }
        public int N408_FULLT_REIDH_5_13_MATSV_BY { get; set; }
        public int N408_FULLT_REIDH_5_13_FJ_LOK { get; set; }
        public int N408_FULLT_REIDH_5_13_MATS_LOK { get; set; }
        public int N408_FULLT_REIDH_5_13_FJ_VANH { get; set; }
        public int N408_FULLT_REIDH_5_13_FJ_KEYPT { get; set; }
        public int N408_FULLT_REIDH_5_13_KAUPVERD { get; set; }
        public int N408_ONNUR_REIDH_5_13_SKATTMAT { get; set; }
        public int N408_ONNUR_REIDH_5_13_FJ_BYRJU { get; set; }
        public int N408_ONNUR_REIDH_5_13_MATSV_BY { get; set; }
        public int N408_ONNUR_REIDH_5_13_FJ_LOK { get; set; }
        public int N408_ONNUR_REIDH_5_13_MATS_LOK { get; set; }
        public int N408_ONNUR_REIDH_5_13_FJ_VANH { get; set; }
        public int N408_ONNUR_REIDH_5_13_FJ_KEYPT { get; set; }
        public int N408_ONNUR_REIDH_5_13_KAUPVERD { get; set; }
        public int N408_VERDLAUNAHR_5_13_SKATTMAT { get; set; }
        public int N408_VERDLAUNAHR_5_13_FJ_BYRJU { get; set; }
        public int N408_VERDLAUNAHR_5_13_MATSV_BY { get; set; }
        public int N408_VERDLAUNAHR_5_13_FJ_LOK { get; set; }
        public int N408_VERDLAUNAHR_5_13_MATS_LOK { get; set; }
        public int N408_VERDLAUNAHR_5_13_FJ_VANH { get; set; }
        public int N408_VERDLAUNAHR_5_13_FJ_KEYPT { get; set; }
        public int N408_VERDLAUNAHR_5_13_KAUPVERD { get; set; }
        public int N408_KYNBOTAHEST_5_13_SKATTMAT { get; set; }
        public int N408_KYNBOTAHEST_5_13_FJ_BYRJU { get; set; }
        public int N408_KYNBOTAHEST_5_13_MATSV_BY { get; set; }
        public int N408_KYNBOTAHEST_5_13_FJ_LOK { get; set; }
        public int N408_KYNBOTAHEST_5_13_MATS_LOK { get; set; }
        public int N408_KYNBOTAHEST_5_13_FJ_VANH { get; set; }
        public int N408_KYNBOTAHEST_5_13_FJ_KEYPT { get; set; }
        public int N408_KYNBOTAHEST_5_13_KAUPVERD { get; set; }
        public int N408_VERDLAUNAKY_5_13_SKATTMAT { get; set; }
        public int N408_VERDLAUNAKY_5_13_FJ_BYRJU { get; set; }
        public int N408_VERDLAUNAKY_5_13_MATSV_BY { get; set; }
        public int N408_VERDLAUNAKY_5_13_FJ_LOK { get; set; }
        public int N408_VERDLAUNAKY_5_13_MATS_LOK { get; set; }
        public int N408_VERDLAUNAKY_5_13_FJ_VANH { get; set; }
        public int N408_VERDLAUNAKY_5_13_FJ_KEYPT { get; set; }
        public int N408_VERDLAUNAKY_5_13_KAUPVERD { get; set; }
        public int N408_TRYPPI_2_4_SKATTMAT { get; set; }
        public int N408_TRYPPI_2_4_FJ_BYRJU { get; set; }
        public int N408_TRYPPI_2_4_MATSV_BY { get; set; }
        public int N408_TRYPPI_2_4_FJ_LOK { get; set; }
        public int N408_TRYPPI_2_4_MATS_LOK { get; set; }
        public int N408_TRYPPI_2_4_FJ_VANH { get; set; }
        public int N408_TRYPPI_2_4_FJ_KEYPT { get; set; }
        public int N408_TRYPPI_2_4_KAUPVERD { get; set; }
        public int N408_FOLOLD_SKATTMAT { get; set; }
        public int N408_FOLOLD_FJ_BYRJU { get; set; }
        public int N408_FOLOLD_MATSV_BY { get; set; }
        public int N408_FOLOLD_FJ_LOK { get; set; }
        public int N408_FOLOLD_MATS_LOK { get; set; }
        public int N408_FOLOLD_FJ_VANH { get; set; }
        public int N408_FOLOLD_FJ_KEYPT { get; set; }
        public int N408_FOLOLD_KAUPVERD { get; set; }
        public int N408_HAENSNI_Y6_SKATTMAT { get; set; }
        public int N408_HAENSNI_Y6_FJ_BYRJU { get; set; }
        public int N408_HAENSNI_Y6_MATSV_BY { get; set; }
        public int N408_HAENSNI_Y6_FJ_LOK { get; set; }
        public int N408_HAENSNI_Y6_MATS_LOK { get; set; }
        public int N408_HAENSNI_Y6_FJ_VANH { get; set; }
        public int N408_HAENSNI_Y6_FJ_KEYPT { get; set; }
        public int N408_HAENSNI_Y6_KAUPVERD { get; set; }
        public int N408_VARPHAENSNI_6U_SKATTMAT { get; set; }
        public int N408_VARPHAENSNI_6U_FJ_BYRJU { get; set; }
        public int N408_VARPHAENSNI_6U_MATSV_BY { get; set; }
        public int N408_VARPHAENSNI_6U_FJ_LOK { get; set; }
        public int N408_VARPHAENSNI_6U_MATS_LOK { get; set; }
        public int N408_VARPHAENSNI_6U_FJ_VANH { get; set; }
        public int N408_VARPHAENSNI_6U_FJ_KEYPT { get; set; }
        public int N408_VARPHAENSNI_6U_KAUPVERD { get; set; }
        public int N408_KJUKLINGAR_SKATTMAT { get; set; }
        public int N408_KJUKLINGAR_FJ_BYRJU { get; set; }
        public int N408_KJUKLINGAR_MATSV_BY { get; set; }
        public int N408_KJUKLINGAR_FJ_LOK { get; set; }
        public int N408_KJUKLINGAR_MATS_LOK { get; set; }
        public int N408_KJUKLINGAR_FJ_VANH { get; set; }
        public int N408_KJUKLINGAR_FJ_KEYPT { get; set; }
        public int N408_KJUKLINGAR_KAUPVERD { get; set; }
        public int N408_ENDUR_SKATTMAT { get; set; }
        public int N408_ENDUR_FJ_BYRJU { get; set; }
        public int N408_ENDUR_MATSV_BY { get; set; }
        public int N408_ENDUR_FJ_LOK { get; set; }
        public int N408_ENDUR_MATS_LOK { get; set; }
        public int N408_ENDUR_FJ_VANH { get; set; }
        public int N408_ENDUR_FJ_KEYPT { get; set; }
        public int N408_ENDUR_KAUPVERD { get; set; }
        public int N408_GAESIR_SKATTMAT { get; set; }
        public int N408_GAESIR_FJ_BYRJU { get; set; }
        public int N408_GAESIR_MATSV_BY { get; set; }
        public int N408_GAESIR_FJ_LOK { get; set; }
        public int N408_GAESIR_MATS_LOK { get; set; }
        public int N408_GAESIR_FJ_VANH { get; set; }
        public int N408_GAESIR_FJ_KEYPT { get; set; }
        public int N408_GAESIR_KAUPVERD { get; set; }
        public int N408_KALKUNAR_SKATTMAT { get; set; }
        public int N408_KALKUNAR_FJ_BYRJU { get; set; }
        public int N408_KALKUNAR_MATSV_BY { get; set; }
        public int N408_KALKUNAR_FJ_LOK { get; set; }
        public int N408_KALKUNAR_MATS_LOK { get; set; }
        public int N408_KALKUNAR_FJ_VANH { get; set; }
        public int N408_KALKUNAR_FJ_KEYPT { get; set; }
        public int N408_KALKUNAR_KAUPVERD { get; set; }
        public int N408_GYLTUR_SKATTMAT { get; set; }
        public int N408_GYLTUR_FJ_BYRJU { get; set; }
        public int N408_GYLTUR_MATSV_BY { get; set; }
        public int N408_GYLTUR_FJ_LOK { get; set; }
        public int N408_GYLTUR_MATS_LOK { get; set; }
        public int N408_GYLTUR_FJ_VANH { get; set; }
        public int N408_GYLTUR_FJ_KEYPT { get; set; }
        public int N408_GYLTUR_KAUPVERD { get; set; }
        public int N408_GELTIR_SKATTMAT { get; set; }
        public int N408_GELTIR_FJ_BYRJU { get; set; }
        public int N408_GELTIR_MATSV_BY { get; set; }
        public int N408_GELTIR_FJ_LOK { get; set; }
        public int N408_GELTIR_MATS_LOK { get; set; }
        public int N408_GELTIR_FJ_VANH { get; set; }
        public int N408_GELTIR_FJ_KEYPT { get; set; }
        public int N408_GELTIR_KAUPVERD { get; set; }
        public int N408_GRISIR_SKATTMAT { get; set; }
        public int N408_GRISIR_FJ_BYRJU { get; set; }
        public int N408_GRISIR_MATSV_BY { get; set; }
        public int N408_GRISIR_FJ_LOK { get; set; }
        public int N408_GRISIR_MATS_LOK { get; set; }
        public int N408_GRISIR_FJ_VANH { get; set; }
        public int N408_GRISIR_FJ_KEYPT { get; set; }
        public int N408_GRISIR_KAUPVERD { get; set; }
        public int N408_KANINUR_SKATTMAT { get; set; }
        public int N408_KANINUR_FJ_BYRJU { get; set; }
        public int N408_KANINUR_MATSV_BY { get; set; }
        public int N408_KANINUR_FJ_LOK { get; set; }
        public int N408_KANINUR_MATS_LOK { get; set; }
        public int N408_KANINUR_FJ_VANH { get; set; }
        public int N408_KANINUR_FJ_KEYPT { get; set; }
        public int N408_KANINUR_KAUPVERD { get; set; }
        public int N408_MINKAR_KK_SKATTMAT { get; set; }
        public int N408_MINKAR_KK_FJ_BYRJU { get; set; }
        public int N408_MINKAR_KK_MATSV_BY { get; set; }
        public int N408_MINKAR_KK_FJ_LOK { get; set; }
        public int N408_MINKAR_KK_MATS_LOK { get; set; }
        public int N408_MINKAR_KK_FJ_VANH { get; set; }
        public int N408_MINKAR_KK_FJ_KEYPT { get; set; }
        public int N408_MINKAR_KK_KAUPVERD { get; set; }
        public int N408_MINKAR_KVK_SKATTMAT { get; set; }
        public int N408_MINKAR_KVK_FJ_BYRJU { get; set; }
        public int N408_MINKAR_KVK_MATSV_BY { get; set; }
        public int N408_MINKAR_KVK_FJ_LOK { get; set; }
        public int N408_MINKAR_KVK_MATS_LOK { get; set; }
        public int N408_MINKAR_KVK_FJ_VANH { get; set; }
        public int N408_MINKAR_KVK_FJ_KEYPT { get; set; }
        public int N408_MINKAR_KVK_KAUPVERD { get; set; }
        public int N408_MINKAR_HVOLPAR_SKATTMAT { get; set; }
        public int N408_MINKAR_HVOLPAR_FJ_BYRJU { get; set; }
        public int N408_MINKAR_HVOLPAR_MATSV_BY { get; set; }
        public int N408_MINKAR_HVOLPAR_FJ_LOK { get; set; }
        public int N408_MINKAR_HVOLPAR_MATS_LOK { get; set; }
        public int N408_MINKAR_HVOLPAR_FJ_VANH { get; set; }
        public int N408_MINKAR_HVOLPAR_FJ_KEYPT { get; set; }
        public int N408_MINKAR_HVOLPAR_KAUPVERD { get; set; }
        public int N408_REFIR_KK_KVK_SKATTMAT { get; set; }
        public int N408_REFIR_KK_KVK_FJ_BYRJU { get; set; }
        public int N408_REFIR_KK_KVK_MATSV_BY { get; set; }
        public int N408_REFIR_KK_KVK_FJ_LOK { get; set; }
        public int N408_REFIR_KK_KVK_MATS_LOK { get; set; }
        public int N408_REFIR_KK_KVK_FJ_VANH { get; set; }
        public int N408_REFIR_KK_KVK_FJ_KEYPT { get; set; }
        public int N408_REFIR_KK_KVK_KAUPVERD { get; set; }
        public int N408_REFIR_HVOLPAR_SKATTMAT { get; set; }
        public int N408_REFIR_HVOLPAR_FJ_BYRJU { get; set; }
        public int N408_REFIR_HVOLPAR_MATSV_BY { get; set; }
        public int N408_REFIR_HVOLPAR_FJ_LOK { get; set; }
        public int N408_REFIR_HVOLPAR_MATS_LOK { get; set; }
        public int N408_REFIR_HVOLPAR_FJ_VANH { get; set; }
        public int N408_REFIR_HVOLPAR_FJ_KEYPT { get; set; }
        public int N408_REFIR_HVOLPAR_KAUPVERD { get; set; }
        public int N408_ONNUR_DYR_SKATTMAT { get; set; }
        public int N408_ONNUR_DYR_FJ_BYRJU { get; set; }
        public int N408_ONNUR_DYR_MATSV_BY { get; set; }
        public int N408_ONNUR_DYR_FJ_LOK { get; set; }
        public int N408_ONNUR_DYR_MATS_LOK { get; set; }
        public int N408_ONNUR_DYR_FJ_VANH { get; set; }
        public int N408_ONNUR_DYR_FJ_KEYPT { get; set; }
        public int N408_ONNUR_DYR_KAUPVERD { get; set; }
        public int N408_BUSTOFNSE_BYRJ_MATSV_SAMT { get; set; }
        public int N408_BUSTOFNSE_LOK_MATSV_SAMT { get; set; }
        public int N408_KEYPT_BUFE_SAMTALS { get; set; }
        public int N408_BUSTOFNSBREYTING_2 { get; set; }

    }
}
