using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FN.Framtal.Database
{
    public class RSK408_MASTER
    {
        public int N408_TENGING_VID_405 { get; set; }
        public string I408_ADAL_BUGREIN_NUMER { get; set; }
        public string T408_ADAL_BUG_HEITI { get; set; }
        public string K408_LANDNUMER { get; set; }
        public string T408_VSK_NUMER { get; set; }
        public int N408_MJOLK_245 { get; set; }
        public int N408_MJOLK_14 { get; set; }
        public int N408_MJOLK_0 { get; set; }
        public int N408_MJOLK_SAMTALS { get; set; }
        public int N408_NAUTGRIPAAFURDIR_245 { get; set; }
        public int N408_NAUTGRIPAAFURDIR_14 { get; set; }
        public int N408_NAUTGRIPAAFURDIR_0 { get; set; }
        public int N408_NAUTGRIPAAFURDIR_SAMTALS { get; set; }
        public int N408_SAUDFJARAFURDIR_245 { get; set; }
        public int N408_SAUDFJARAFURDIR_14 { get; set; }
        public int N408_SAUDFJARAFURDIR_0 { get; set; }
        public int N408_SAUDFJARAFURDIR_SAMTALS { get; set; }
        public int N408_HROSSAAFURDIR_245 { get; set; }
        public int N408_HROSSAAFURDIR_14 { get; set; }
        public int N408_HROSSAAFURDIR_0 { get; set; }
        public int N408_HROSSAAFURDIR_SAMTALS { get; set; }
        public int N408_SVINAAFURDIR_245 { get; set; }
        public int N408_SVINAAFURDIR_14 { get; set; }
        public int N408_SVINAAFURDIR_0 { get; set; }
        public int N408_SVINAAFURDIR_SAMTALS { get; set; }
        public int N408_ALIFUGLAAFURDIR_245 { get; set; }
        public int N408_ALIFUGLAAFURDIR_14 { get; set; }
        public int N408_ALIFUGLAAFURDIR_0 { get; set; }
        public int N408_ALIFUGLAAFURDIR_SAMTALS { get; set; }
        public int N408_EGG_245 { get; set; }
        public int N408_EGG_14 { get; set; }
        public int N408_EGG_0 { get; set; }
        public int N408_EGG_SAMTALS { get; set; }
        public int N408_KARTOFLUR_245 { get; set; }
        public int N408_KARTOFLUR_14 { get; set; }
        public int N408_KARTOFLUR_0 { get; set; }
        public int N408_KARTOFLUR_SAMTALS { get; set; }
        public int N408_GULROFUR_245 { get; set; }
        public int N408_GULROFUR_14 { get; set; }
        public int N408_GULROFUR_0 { get; set; }
        public int N408_GULROFUR_SAMTALS { get; set; }
        public int N408_ANNAD_GRAENMETI_BLOM_245 { get; set; }
        public int N408_ANNAD_GRAENMETI_BLOM_14 { get; set; }
        public int N408_ANNAD_GRAENMETI_BLOM_0 { get; set; }
        public int N408_ANNAD_GRAENMETI_BLOM_SAMT { get; set; }
        public int N408_GRAVARA_245 { get; set; }
        public int N408_GRAVARA_0 { get; set; }
        public int N408_GRAVARA_SAMTALS { get; set; }
        public int N408_AEDARDUNN_245 { get; set; }
        public int N408_AEDARDUNN_0 { get; set; }
        public int N408_AEDARDUNN_SAMTALS { get; set; }
        public int N408_SKOGARAFURDIR_245 { get; set; }
        public int N408_SKOGARAFURDIR_14 { get; set; }
        public int N408_SKOGARAFURDIR_0 { get; set; }
        public int N408_SKOGARAFURDIR_SAMTALS { get; set; }
        public int N408_HEYSALA_ADRAR_TEKJUR_245 { get; set; }
        public int N408_HEYSALA_ADRAR_TEKJUR_14 { get; set; }
        public int N408_HEYSALA_ADRAR_TEKJUR_0 { get; set; }
        public int N408_HEYSALA_ADRAR_TEKJUR_SAMT { get; set; }
        public int N408_VELTA_0 { get; set; }
        public int N408_VELTA_SAMTALS { get; set; }
        public int N408_SOLUHAGNADUR_0 { get; set; }
        public int N408_SOLUHAGNADUR_SAMTALS { get; set; }
        public int N408_ADRAR_TEKJUR_245 { get; set; }
        public int N408_ADRAR_TEKJUR_14 { get; set; }
        public int N408_ADRAR_TEKJUR_0 { get; set; }
        public int N408_ADRAR_TEKJUR_SAMTALS { get; set; }
        public int N408_REKSTRARTEKJUR_245 { get; set; }
        public int N408_REKSTRARTEKJUR_14 { get; set; }
        public int N408_REKSTRARTEKJUR_0 { get; set; }
        public int N408_REKSTRARTEKJUR_SAMTALS { get; set; }
        public int N408_FODUR_245 { get; set; }
        public int N408_FODUR_14 { get; set; }
        public int N408_FODUR_0 { get; set; }
        public int N408_FODUR_SAMTALS { get; set; }
        public int N408_HEYKAUP_245 { get; set; }
        public int N408_HEYKAUP_0 { get; set; }
        public int N408_HEYKAUP_SAMTALS { get; set; }
        public int N408_ABURDUR_SADVORUR_245 { get; set; }
        public int N408_ABURDUR_SADVORUR_14 { get; set; }
        public int N408_ABURDUR_SADVORUR_0 { get; set; }
        public int N408_ABURDUR_SADVORUR_SAMTALS { get; set; }
        public int N408_SLAEGJUR_BEIT_245 { get; set; }
        public int N408_SLAEGJUR_BEIT_0 { get; set; }
        public int N408_SLAEGJUR_BEIT_SAMTALS { get; set; }
        public int N408_BUVELAR_BIFREIDAR_245 { get; set; }
        public int N408_BUVELAR_BIFREIDAR_14 { get; set; }
        public int N408_BUVELAR_BIFREIDAR_0 { get; set; }
        public int N408_BUVELAR_BIFREIDAR_SAMTALS { get; set; }
        public int N408_REKSTRARVORUR_245 { get; set; }
        public int N408_REKSTRARVORUR_14 { get; set; }
        public int N408_REKSTRARVORUR_0 { get; set; }
        public int N408_REKSTRARVORUR_SAMTALS { get; set; }
        public int N408_FJALLSKIL_245 { get; set; }
        public int N408_FJALLSKIL_0 { get; set; }
        public int N408_FJALLSKIL_SAMTALS { get; set; }
        public int N408_SLATURKOSTNADUR_245 { get; set; }
        public int N408_SLATURKOSTNADUR_0 { get; set; }
        public int N408_SLATURKOSTNADUR_SAMTALS { get; set; }
        public int N408_FLUTNINGSKOSTNADUR_245 { get; set; }
        public int N408_FLUTNINGSKOSTNADUR_0 { get; set; }
        public int N408_FLUTNINGSKOSTNADUR_SAMT { get; set; }
        public int N408_ADKEYPT_THJONUSTA_245 { get; set; }
        public int N408_ADKEYPT_THJONUSTA_0 { get; set; }
        public int N408_ADKEYPT_THJONUSTA_SAMTALS { get; set; }
        public int N408_VIDHALD_HUSNAEDIS_245 { get; set; }
        public int N408_VIDHALD_HUSNAEDIS_0 { get; set; }
        public int N408_VIDHALD_HUSNAEDIS_SAMTALS { get; set; }
        public int N408_REKSTRARK_HUSNAEDIS_245 { get; set; }
        public int N408_REKSTRARK_HUSNAEDIS_14 { get; set; }
        public int N408_REKSTRARK_HUSNAEDIS_0 { get; set; }
        public int N408_REKSTRARK_HUSNAEDIS_SAMT { get; set; }
        public int N408_KAUPVERD_LIFDYRA_245 { get; set; }
        public int N408_KAUPVERD_LIFDYRA_0 { get; set; }
        public int N408_KAUPVERD_LIFDYRA_SAMTALS { get; set; }
        public int N408_TAEKJA_FJARM_LEIGA_245 { get; set; }
        public int N408_TAEKJA_FJARM_LEIGA_0 { get; set; }
        public int N408_TAEKJA_FJARM_LEIGA_SAMT { get; set; }
        public int N408_LEIGA_JARDARAFGJALD_245 { get; set; }
        public int N408_LEIGA_JARDARAFGJALD_0 { get; set; }
        public int N408_LEIGA_JARDARAFGJALD_SAMT { get; set; }
        public int N408_AFSKRIF_VIDSKIPTAK_245 { get; set; }
        public int N408_AFSKRIF_VIDSKIPTAK_14 { get; set; }
        public int N408_AFSKRIF_VIDSKIPTAK_0 { get; set; }
        public int N408_AFSKRIF_VIDSKIPTAK_SAMT { get; set; }
        public int N408_ANNAR_KOSTNADUR_245 { get; set; }
        public int N408_ANNAR_KOSTNADUR_14 { get; set; }
        public int N408_ANNAR_KOSTNADUR_0 { get; set; }
        public int N408_ANNAR_KOSTNADUR_SAMTALS { get; set; }
        public int N408_REKSTRARGJOLD_245 { get; set; }
        public int N408_REKSTRARGJOLD_14 { get; set; }
        public int N408_REKSTRARGJOLD_0 { get; set; }
        public int N408_REKSTRARG_MTT_VSK_SAMTALS { get; set; }
        public int N408_REIKNAD_ENDURGJALD_1 { get; set; }
        public int N408_LAUN { get; set; }
        public int N408_MOTFRAMLAG_LIFEYRISSJOD { get; set; }
        public int N408_LAUNATENGD_GJOLD { get; set; }
        public int N408_TRYGGINGAR { get; set; }
        public int N408_BUNADARGJALD { get; set; }
        public int N408_FELAGSGJOLD { get; set; }
        public int N408_BIFREIDAKOSTNADUR { get; set; }
        public int N408_ALM_FYRNINGAR_SKV_EIGNAS { get; set; }
        public int N408_AUKAFYRN_SKV_EIGNASKRA { get; set; }
        public int N408_REKSTRARGJOLD_SAMTALS { get; set; }
        public int N408_REKSTRARTEK_MIN_REKSTRARG { get; set; }
        public int N408_ADRAR_FJARMUNATEKJUR { get; set; }
        public int N408_ONNUR_FJARMAGNSGJOLD { get; set; }
        public int N408_BIRGDABREYTING { get; set; }
        public int N408_BUSTOFNSBREYTING_1 { get; set; }
        public int N408_SOLUTAP { get; set; }
        public int N408_ADRAR_TEKJUR_GJOLD_SAMT { get; set; }
        public int N408_HAGNADUR_TAP_REKSTUR { get; set; }
        public int N408_NIDURF_VKR_UPPH_ARS { get; set; }
        public int N408_NIDURF_VKR_LOK_ARS { get; set; }
        public int N408_NIDURF_BIRG_UPPHAFI_ARS { get; set; }
        public int N408_NIDURF_BIRG_LOK_ARS { get; set; }
        public int N408_FRESTUN_SOLUHAGNADAR { get; set; }
        public int N408_TEKJUF_SOLUH_FRA_FYRRI_AR { get; set; }
        public int N408_ALAG_V_FRESTADS_SOLUH { get; set; }
        public int N408_LEIDR_TEKJUR_SBR_SUNDURL { get; set; }
        public int N408_HR_TEKJU_YFIRF_TAP_T_N_AR { get; set; }
        public int N408_SJODIR_FE_STADGREIDSLA { get; set; }
        public int N408_SJODIR_FE_VEXTIR { get; set; }
        public int N408_SJODIR_FE_EIGNIR { get; set; }
        public int N408_BIRGDIR_SKV_BIRGDATOFLU { get; set; }
        public int N408_VIDSKIPTAK_STADGREIDSLA { get; set; }
        public int N408_VIDSKIPTAK_VEXTIR { get; set; }
        public int N408_VIDSKIPTAK_EIGNIR { get; set; }
        public int N408_ADRAR_PENINGAL_STADG { get; set; }
        public int N408_ADRAR_PENINGAL_VEXTIR { get; set; }
        public int N408_ADRAR_PENINGAL_EIGNIR { get; set; }
        public int N408_EIGNARHLUTIR_STADG { get; set; }
        public int N408_EIGNARHLUTIR_VEXTIR { get; set; }
        public int N408_EIGNARHLUTIR_EIGNIR { get; set; }
        public int N408_BUSTOFN_SKV_BUSTOFNSS { get; set; }
        public int N408_EIGNIR_SKV_EIGNASKRA { get; set; }
        public int N408_ADRAR_EIGNIR_STADGREIDSLA { get; set; }
        public int N408_ADRAR_EIGNIR_VEXTIR { get; set; }
        public int N408_ADRAR_EIGNIR_EIGNIR { get; set; }
        public int N408_EIGNIR_SAMT_STADGREIDSLA { get; set; }
        public int N408_EIGNIR_SAMT_VEXTIR { get; set; }
        public int N408_EIGNIR_SAMT_SAMTALS { get; set; }
        public int N408_LANASJODUR_LANDB_VEXTIR { get; set; }
        public int N408_LANASJODUR_LANDB_SKULDIR { get; set; }
        public int N408_SKULDIR_LANAS_VEXTIR { get; set; }
        public int N408_SKULDIR_LANAS_SKULDIR { get; set; }
        public int N408_VIDSKIPTASKULDIR_VEXTIR { get; set; }
        public int N408_VIDSKIPTASKULDIR_SKULDIR { get; set; }
        public int N408_OGREIDDUR_VSK_VEXTIR { get; set; }
        public int N408_OGREIDDUR_VSK_SKULDIR { get; set; }
        public int N408_ADRAR_SKULDIR_VEXTIR { get; set; }
        public int N408_ADRAR_SKULDIR_SKULDIR { get; set; }
        public int N408_SKULDIR_SAMTALS_VEXTIR { get; set; }
        public int N408_SKULDIR_SAMTALS_SKULDIR { get; set; }
        public int N408_EIGID_FE_ARSBYRJUN { get; set; }
        public int N408_HAGNADUR_TAP { get; set; }
        public int N408_REIKNAD_ENDURGJALD_2 { get; set; }
        public int N408_UTTEKT_FRAMLAG { get; set; }
        public int N408_ADRAR_BREYTINGAR_EIGID_FE { get; set; }
        public int N408_EIGID_FE_SAMTALS { get; set; }
        public int N408_NIDURFAERSLA_VIDSKIPTAK { get; set; }
        public int N408_NIDURFAERSLA_BIRGDA { get; set; }
        public int N408_BOKFAERTVERD_FASTEIGNA { get; set; }
        public int N408_OMETNAR_FRAMKVAEMDIR { get; set; }
        public int N408_FASTEIGNIR_FASTEIGNAMAT { get; set; }
        public int N408_LEIDR_EIGN_SBR_SUNDURL { get; set; }
        public int N408_HREIN_EIGN_SKULD_UMFR_EIG { get; set; }
        public int N408_GARDRAEKT_BIRGDIR_LOK { get; set; }
        public int N408_GARDRAEKT_BIRGDIR_BYRJUN { get; set; }
        public int N408_GARDRAEKT_BIRGDIR_MISM { get; set; }
        public int N408_REKSTRARV_BIRGDIR_LOK { get; set; }
        public int N408_REKSTRARV_BIRGDIR_BYRJUN { get; set; }
        public int N408_REKSTRARV_BIRGDIR_MISM { get; set; }
        public int N408_UMSYSLUKJOT_BIRGDIR_LOK { get; set; }
        public int N408_UMSYSLUKJOT_BIRGDIR_BYR { get; set; }
        public int N408_UMSYSLUKJOT_BIRGDIR_MISM { get; set; }
        public int N408_ANNAD_BIRGDIR_LOK { get; set; }
        public int N408_ANNAD_BIRGDIR_BYRJUN { get; set; }
        public int N408_ANNAD_BIRGDIR_MISMUNUR { get; set; }
        public int N408_SAMTALS_BIRGDIR_LOK { get; set; }
        public int N408_SAMTALS_BIRGDIR_BYRJUN { get; set; }
        public int N408_SAMTALS_BIRGDIR_MISMUNUR { get; set; }
        public int N408_VSK_SALA_245_BOKHALD { get; set; }
        public int N408_VSK_SALA_245_SKYRSLUM { get; set; }
        public int N408_VSK_SALA_245_MISMUNUR { get; set; }
        public int N408_VSK_SALA_14_BOKHALD { get; set; }
        public int N408_VSK_SALA_14_SKYRSLUM { get; set; }
        public int N408_VSK_SALA_14_MISMUNUR { get; set; }
        public int N408_VSK_SALA_0_BOKHALD { get; set; }
        public int N408_VSK_SALA_0_SKYRSLUM { get; set; }
        public int N408_VSK_SALA_0_MISMUNUR { get; set; }
        public int N408_UTSKATTUR_BOKHALD { get; set; }
        public int N408_UTSKATTUR_SKYRSLUM { get; set; }
        public int N408_UTSKATTUR_MISMUNUR { get; set; }
        public int N408_REIKNADUR_INNSKATTUR { get; set; }
        public int N408_LEIDR_INNSKATT_SBR_SUNDUR { get; set; }
        public int N408_INNSKATTUR_BOKHALD { get; set; }
        public int N408_INNSKATTUR_SKYRSLUM { get; set; }
        public int N408_INNSKATTUR_MISMUNUR { get; set; }
        public int N408_MJOLK_MJOLKURAF_BEINGR_FL { get; set; }
        public int N408_NAUTGRIPAAF_ADRAR_FL { get; set; }
        public int N408_SAUDFJARAF_BEINGR_FL { get; set; }
        public int N408_HROSSAAFURDIR_FL { get; set; }
        public int N408_SVINAAFURDIR_FL { get; set; }
        public int N408_ALIFUGLAR_MINUS_EGG_FL { get; set; }
        public int N408_EGG_FL { get; set; }
        public int N408_KARTOFLUR_FL { get; set; }
        public int N408_GULROFUR_FL { get; set; }
        public int N408_ANNAD_GRAENMETI_BLOM_FL { get; set; }
        public int N408_GRAVARA_FL { get; set; }
        public int N408_AEDARDUNN_FL { get; set; }
        public int N408_SKOGARAFURDIR_FL { get; set; }
        public int N408_HEYSALA_ADRAR_TEKJUR_FL { get; set; }
        public int N408_MJOLK_MJOLKURAF_BEINGR_LA { get; set; }
        public int N408_NAUTGRIPAAF_ADRAR_LA { get; set; }
        public int N408_SAUDFJARAF_BEINGR_LA { get; set; }
        public int N408_HROSSAAFURDIR_LA { get; set; }
        public int N408_SVINAAFURDIR_LA { get; set; }
        public int N408_ALIFUGLAR_MINUS_EGG_LA { get; set; }
        public int N408_EGG_LA { get; set; }
        public int N408_KARTOFLUR_LA { get; set; }
        public int N408_GULROFUR_LA { get; set; }
        public int N408_ANNAD_GRAENMETI_BLOM_LA { get; set; }
        public int N408_GRAVARA_LA { get; set; }
        public int N408_AEDARDUNN_LA { get; set; }
        public int N408_SKOGARAFURDIR_LA { get; set; }
        public int N408_HEYSALA_ADRAR_TEKJUR_LA { get; set; }
        public int N408_NAUTGRIPAAF_ADRAR_FR { get; set; }
        public int N408_SAUDFJARAF_BEINGR_FR { get; set; }
        public int N408_HROSSAAFURDIR_FR { get; set; }
        public int N408_SVINAAFURDIR_FR { get; set; }
        public int N408_ALIFUGLAR_MINUS_EGG_FR { get; set; }
        public int N408_EGG_FR { get; set; }
        public int N408_KARTOFLUR_FR { get; set; }
        public int N408_GULROFUR_FR { get; set; }
        public int N408_ANNAD_GRAENMETI_BLOM_FR { get; set; }
        public int N408_GRAVARA_FR { get; set; }
        public int N408_AEDARDUNN_FR { get; set; }
        public int N408_SKOGARAFURDIR_FR { get; set; }
        public int N408_HEYSALA_ADRAR_TEKJUR_FR { get; set; }
        public int N408_MJOLK_MJOLKURAF_BEINGR_ST { get; set; }
        public int N408_NAUTGRIPAAF_ADRAR_ST { get; set; }
        public int N408_SAUDFJARAF_BEINGR_ST { get; set; }
        public int N408_HROSSAAFURDIR_ST { get; set; }
        public int N408_SVINAAFURDIR_ST { get; set; }
        public int N408_ALIFUGLAR_MINUS_EGG_ST { get; set; }
        public int N408_EGG_ST { get; set; }
        public int N408_KARTOFLUR_ST { get; set; }
        public int N408_GULROFUR_ST { get; set; }
        public int N408_ANNAD_GRAENMETI_BLOM_ST { get; set; }
        public int N408_GRAVARA_ST { get; set; }
        public int N408_AEDARDUNN_ST { get; set; }
        public int N408_SKOGARAFURDIR_ST { get; set; }
        public int N408_HEYSALA_ADRAR_TEKJUR_ST { get; set; }
        public int N408_BUNADARGJALDSSTOFN { get; set; }
        public int N408_STADGREIDSL_FJMTSK_AF_ARD { get; set; }
        public int N408_STADGREI_FJMTSK_AF_VOXTUM { get; set; }
        public string M408_ATH { get; set; }
    }
}
