namespace FN.Framtal.Domain._2004.Validation
{
    public class RSK405_MASTER
    {
        public int N405_SAMTALA_HREIN_EIGN_SKULD { get; set; }
        public int N405_SAMTALS_REKSTRARHAGN_TAP { get; set; }
        public int N405_SAMT_REIKN_ENDURG_EIGID { get; set; }
        public int N405_SAMTALS_REIKN_ENDURG_MAKA { get; set; }
        public int N405_ONOTAD_TAP_MIN_9 { get; set; }
        public int N405_YFIRFAERANLEGT_MIN_9 { get; set; }
        public int N405_ONOTAD_TAP_MIN_8 { get; set; }
        public int N405_YFIRFAERANLEGT_MIN_8 { get; set; }
        public int N405_ONOTAD_TAP_MIN_7 { get; set; }
        public int N405_YFIRFAERANLEGT_MIN_7 { get; set; }
        public int N405_ONOTAD_TAP_MIN_6 { get; set; }
        public int N405_YFIRFAERANLEGT_MIN_6 { get; set; }
        public int N405_ONOTAD_TAP_MIN_5 { get; set; }
        public int N405_YFIRFAERANLEGT_MIN_5 { get; set; }
        public int N405_ONOTAD_TAP_MIN_4 { get; set; }
        public int N405_YFIRFAERANLEGT_MIN_4 { get; set; }
        public int N405_ONOTAD_TAP_MIN_3 { get; set; }
        public int N405_YFIRFAERANLEGT_MIN_3 { get; set; }
        public int N405_ONOTAD_TAP_MIN_2 { get; set; }
        public int N405_YFIRFAERANLEGT_MIN_2 { get; set; }
        public int N405_ONOTAD_TAP_MIN_1 { get; set; }
        public int N405_YFIRFAERANLEGT_MIN_1 { get; set; }
        public int N405_SAMTALS_TAP_ARSINS { get; set; }
        public string M405_ATH { get; set; }
        public int N405_IDNADARMALAGJALDSTOFN { get; set; }
        public int N405_LAEKKUN_AUKAFYRNINGA_EIGN { get; set; }
        public int N405_EIGN_SKULDIR { get; set; }
        public int N405_REIKNAD_ENDURGJALD { get; set; }
        public int N405_LAEKKUN_REIKN_ENDURGJ { get; set; }
        public int N405_LAEKKUN_AUKAFYRNINGA_TEKJ { get; set; }
        public int N405_LAEKKUN_FREST_SOLUH { get; set; }
        public int N405_LAEKK_REIKN_ENDURGJ_TAP { get; set; }
        public int N405_HAGNADUR_TAP { get; set; }
        public int N405_HREINAR_TEKJUR_TAP { get; set; }
        public int N405_STADGR_AF_ARDI { get; set; }
        public int N405_STADGR_AF_VOXTUM { get; set; }
        public int N405_STADGR_FJTEKJUSKATT { get; set; }
        public int N405_BUNADARGJALDSSTOFN { get; set; }
        public int N405_ONOTAD_TAP_MIN_10 { get; set; }
        public int N405_REIKNAD_EIGID_ENDURGJALD { get; set; }
        public int N405_LEIDR_GJALDST_LAGM_TRYGG { get; set; }
        public int N405_MOTFRAMLAG_REIKN_ENDURGJ { get; set; }
        public int N405_STOFN_TRYGG_GJ_STGR_1 { get; set; }
        public int N405_STOFN_TRYGG_GJ_UT_STGR_1 { get; set; }
        public int N405_EIGIN_REIKN_LAUN_JAN { get; set; }
        public int N405_EIGIN_REIKN_LAUN_FEB { get; set; }
        public int N405_EIGIN_REIKN_LAUN_MAR { get; set; }
        public int N405_EIGIN_REIKN_LAUN_APR { get; set; }
        public int N405_EIGIN_REIKN_LAUN_MAI { get; set; }
        public int N405_EIGIN_REIKN_LAUN_JUN { get; set; }
        public int N405_EIGIN_REIKN_LAUN_JUL { get; set; }
        public int N405_EIGIN_REIKN_LAUN_AGU { get; set; }
        public int N405_EIGIN_REIKN_LAUN_SEP { get; set; }
        public int N405_EIGIN_REIKN_LAUN_OKT { get; set; }
        public int N405_EIGIN_REIKN_LAUN_NOV { get; set; }
        public int N405_EIGIN_REIKN_LAUN_DES { get; set; }
        public int N405_EIGIN_REIKN_LAUN_SAMTALS { get; set; }
        public int N405_REIKNAD_ENDURGJ_MAKA { get; set; }
        public int N405_REIKNAD_ENDURGJ_BARNA { get; set; }
        public int N405_LAUN_ANNARRA { get; set; }
        public int N405_OKUTAEKJAST_ANNARRA { get; set; }
        public int N405_ONNUR_LAUN_ANNARRA { get; set; }
        public int N405_REIKNUD_HLUNNINDI_ANNARRA { get; set; }
        public int N405_STGRSKYLDIR_DAGP_ANNARRA { get; set; }
        public int N405_MOTFRAMLAG_LIFEYRISSJOD { get; set; }
        public int N405_MOTFRAMLAG_LIFEYRISS_RE { get; set; }
        public int N405_LAUN_ANNARRA_UNDAN_STADG { get; set; }
        public int N405_REI_HLU_ANNARA_UNDAN_STGR { get; set; }
        public int N405_LEIDR_STOFN_TRYGGINGARGJ { get; set; }
        public int N405_SAMTALS_TRYGGINGARGJALDST { get; set; }
        public int N405_STOFN_TRYGG_GJ_STGR_2 { get; set; }
        public int N405_STOFN_TRYGG_GJ_UT_STGR_2 { get; set; }
        public int N405_STOFN_TRYGG_STADGR_JAN { get; set; }
        public int N405_STOFN_TRYGG_STADGR_FEB { get; set; }
        public int N405_STOFN_TRYGG_STADGR_MAR { get; set; }
        public int N405_STOFN_TRYGG_STADGR_APR { get; set; }
        public int N405_STOFN_TRYGG_STADGR_MAI { get; set; }
        public int N405_STOFN_TRYGG_STADGR_JUN { get; set; }
        public int N405_STOFN_TRYGG_STADGR_JUL { get; set; }
        public int N405_STOFN_TRYGG_STADGR_AGU { get; set; }
        public int N405_STOFN_TRYGG_STADGR_SEP { get; set; }
        public int N405_STOFN_TRYGG_STADGR_OKT { get; set; }
        public int N405_STOFN_TRYGG_STADGR_NOV { get; set; }
        public int N405_STOFN_TRYGG_STADGR_DES { get; set; }
        public int N405_STOFN_TRYGG_STADGR_SAMT { get; set; }
        public int N405_LAUN_VEGNA_FISKVEIDA_JAN { get; set; }
        public int N405_LAUN_VEGNA_FISKVEIDA_FEB { get; set; }
        public int N405_LAUN_VEGNA_FISKVEIDA_MAR { get; set; }
        public int N405_LAUN_VEGNA_FISKVEIDA_APR { get; set; }
        public int N405_LAUN_VEGNA_FISKVEIDA_MAI { get; set; }
        public int N405_LAUN_VEGNA_FISKVEIDA_JUN { get; set; }
        public int N405_LAUN_VEGNA_FISKVEIDA_JUL { get; set; }
        public int N405_LAUN_VEGNA_FISKVEIDA_AGU { get; set; }
        public int N405_LAUN_VEGNA_FISKVEIDA_SEP { get; set; }
        public int N405_LAUN_VEGNA_FISKVEIDA_OKT { get; set; }
        public int N405_LAUN_VEGNA_FISKVEIDA_NOV { get; set; }
        public int N405_LAUN_VEGNA_FISKVEIDA_DES { get; set; }
        public int N405_LAUN_VEGNA_FISKVEIDA_SAMT { get; set; }
        public int N405_STOFN_ALLS_STAGR_JAN { get; set; }
        public int N405_STOFN_ALLS_STAGR_FEB { get; set; }
        public int N405_STOFN_ALLS_STAGR_MAR { get; set; }
        public int N405_STOFN_ALLS_STAGR_APR { get; set; }
        public int N405_STOFN_ALLS_STAGR_MAI { get; set; }
        public int N405_STOFN_ALLS_STAGR_JUN { get; set; }
        public int N405_STOFN_ALLS_STAGR_JUL { get; set; }
        public int N405_STOFN_ALLS_STAGR_AGU { get; set; }
        public int N405_STOFN_ALLS_STAGR_SEP { get; set; }
        public int N405_STOFN_ALLS_STAGR_OKT { get; set; }
        public int N405_STOFN_ALLS_STAGR_NOV { get; set; }
        public int N405_STOFN_ALLS_STAGR_DES { get; set; }
        public int N405_STOFN_ALLS_STAGR_SAMT { get; set; }
        public int N405_ST_TRYGG_GJ_UT_STAGR_SAMT { get; set; }
        public int N405_STOFN_TRYGG_GJ_STGR_3 { get; set; }
        public int N405_STOFN_TRYGG_GJ_UT_STGR_3 { get; set; }


    }
}
